### PR TITLE
Add auto links for descriptions

### PR DESCRIPTION
**Pull request by rawOrlando**
Jira Ticket: https://tuftswork.atlassian.net/jira/software/c/projects/TDLR/boards/58?modal=detail&selectedIssue=TDLR-2446

Makes links clickable in the description field. 

After https://github.com/TuftsUniversity/tdl_on_hyrax/pull/55 had some bugs, this is the rewritten version.

### CODE REVIEW

**Review by mkorcy — APPROVED** [review]
ran the test locally, looked good. thanks for adding.  read more/less could've moved to i8n but fine as is.

**Comment by mkorcy** [comment]
@rawOrlando I looked through the rest of MetadataMethods and I think that code is all unreferenced and can be removed.

**Comment by rawOrlando** [comment]
I was hoping this pr would not balloon. I did notice that comment. Mind if I deploy this and come back to trim the hedges?

**Comment by mkorcy** [comment]
That is fine, I'll put a PR after it to fast follow so we don't lose track while we're here.

**Pull request merged**
